# Generated by Django 4.1.7 on 2023-04-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messagechain_questionanswer_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechain',
            name='job_title',
            field=models.TextField(default='noname'),
        ),
    ]
